<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXDwxB65\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXDwxB65/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXDwxB65.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXDwxB65\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXDwxB65\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XDwxB65',
    'container.build_id' => '6c268593',
    'container.build_time' => 1609844680,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXDwxB65');
