<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Band extends \App\Entity\Band implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'style', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'picture', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'creationYear', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'lastAlbumName', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'members', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'concerts'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'style', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'picture', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'creationYear', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'lastAlbumName', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'members', '' . "\0" . 'App\\Entity\\Band' . "\0" . 'concerts'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Band $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Band
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getStyle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStyle', []);

        return parent::getStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function setStyle(string $style): \App\Entity\Band
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStyle', [$style]);

        return parent::setStyle($style);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', []);

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture(?string $picture): \App\Entity\Band
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', [$picture]);

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationYear(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationYear', []);

        return parent::getCreationYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationYear(?\DateTimeInterface $creationYear): \App\Entity\Band
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationYear', [$creationYear]);

        return parent::setCreationYear($creationYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastAlbumName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastAlbumName', []);

        return parent::getLastAlbumName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastAlbumName(?string $lastAlbumName): \App\Entity\Band
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastAlbumName', [$lastAlbumName]);

        return parent::setLastAlbumName($lastAlbumName);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembers', []);

        return parent::getMembers();
    }

    /**
     * {@inheritDoc}
     */
    public function addMember(\App\Entity\Member $member): \App\Entity\Band
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMember', [$member]);

        return parent::addMember($member);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMember(\App\Entity\Member $member): \App\Entity\Band
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMember', [$member]);

        return parent::removeMember($member);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): ?\App\Entity\Concert
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\App\Entity\Concert $date): \App\Entity\Band
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getConcerts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConcerts', []);

        return parent::getConcerts();
    }

    /**
     * {@inheritDoc}
     */
    public function addConcert(\App\Entity\Concert $concert): \App\Entity\Band
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConcert', [$concert]);

        return parent::addConcert($concert);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConcert(\App\Entity\Concert $concert): \App\Entity\Band
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConcert', [$concert]);

        return parent::removeConcert($concert);
    }

}
